//! Generate a session-bootstrap context markdown file summarizing a project's
//! code graph: node/language/edge distribution, hub entities, and the most
//! coupled files. Pure `code_node` / `code_edge` data — no repo-specific
//! assumptions, so this works for any indexed project.

use anyhow::{Context, Result};
use std::fmt::Write;
use std::path::Path;
use std::sync::Arc;
use surrealdb::engine::any::Any;
use surrealdb::Surreal;

/// Generate the session bootstrap context file for `project_id`.
pub async fn generate_context(
    db: &Arc<Surreal<Any>>,
    project_id: &str,
    output: &Path,
) -> Result<()> {
    let mut md = String::with_capacity(4096);

    writeln!(md, "<!-- AUTO-GENERATED by codegraph. Do not edit. -->")?;
    writeln!(
        md,
        "<!-- Regenerate: codegraph context --project-id {project_id} -->"
    )?;
    writeln!(md, "# Codegraph Context — {project_id}\n")?;

    // Section 1: project summary (node types, languages, edge types)
    let summary = crate::graph::search::project_summary(db, project_id)
        .await
        .context("project_summary query failed")?;

    writeln!(md, "## Project Summary\n")?;
    writeln!(md, "**Node types:**\n")?;
    for (nt, c) in &summary.node_types {
        writeln!(md, "- {nt}: {c}")?;
    }
    writeln!(md, "\n**Languages:**\n")?;
    for (l, c) in &summary.languages {
        writeln!(md, "- {l}: {c}")?;
    }
    writeln!(md, "\n**Edge types:**\n")?;
    for (et, c) in &summary.edge_types {
        writeln!(md, "- {et}: {c}")?;
    }
    writeln!(md)?;

    // Section 2: hub nodes (most-connected entities — architectural hotspots)
    writeln!(md, "## Hub Nodes (top 20)\n")?;
    let hubs = crate::graph::hub_nodes::find_hub_nodes(db, project_id, 20)
        .await
        .context("find_hub_nodes query failed")?;
    for h in &hubs {
        writeln!(
            md,
            "- `{}` ({}) — in:{} out:{} total:{} — {}",
            h.name, h.node_type, h.in_degree, h.out_degree, h.total_degree, h.file_path
        )?;
    }
    writeln!(md)?;

    // Section 3: most-coupled files (afferent + efferent coupling)
    writeln!(md, "## Most Coupled Files (top 15)\n")?;
    let coupling = crate::graph::coupling::calculate_file_coupling(db, project_id, 15)
        .await
        .context("calculate_file_coupling query failed")?;
    writeln!(md, "Ca=afferent (depended on by), Ce=efferent (depends on), I=instability\n")?;
    for c in &coupling {
        writeln!(
            md,
            "- `{}` — Ca:{} Ce:{} I:{:.2} ({} nodes)",
            c.file_path, c.afferent, c.efferent, c.instability, c.node_count
        )?;
    }
    writeln!(md)?;

    // Write to file
    if let Some(parent) = output.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(output, &md)?;
    println!("Context written to {}", output.display());

    Ok(())
}
